const { wrapTrend, wrapMeanRev } = require('./templates');

module.exports = [
  {
    id: 'R1_Donchian20_ATRstop',
    round: 1,
    concept: 'Turtle-style Donchian(20) breakout, ATR(14) 2.5x trailing-equivalent stop',
    hypothesis: 'Classic trend-following breakout should catch BTC\'s large multi-year trend legs even if whipsawed in chop.',
    pineSource: wrapTrend({
      title: 'BTC Donchian20 Breakout',
      inputs: `donLen = input.int(20, "Donchian Length")`,
      indicators: `upperCh = ta.highest(high, donLen)[1]\nlowerCh = ta.lowest(low, donLen)[1]`,
      longCond: 'close > upperCh',
      shortCond: 'close < lowerCh',
      atrMult: 2.5,
    }),
  },
  {
    id: 'R1_SuperTrend_ADX',
    round: 1,
    concept: 'SuperTrend(3, 10) flip filtered by ADX(14) > 20 (only trade confirmed trending regimes)',
    hypothesis: 'Research shows SuperTrend whipsaws badly in chop — an ADX regime filter should cut false flips.',
    pineSource: wrapTrend({
      title: 'BTC SuperTrend ADX',
      inputs: `stMult = input.float(3.0, "ST Mult")\nstLen = input.int(10, "ST Len")\nadxLen = input.int(14, "ADX Len")\nadxTh = input.int(20, "ADX Threshold")`,
      indicators: `[supertrend, direction] = ta.supertrend(stMult, stLen)\n[diPlus, diMinus, adxVal] = ta.dmi(adxLen, adxLen)`,
      longCond: 'ta.crossunder(direction, 0) and adxVal > adxTh',
      shortCond: 'ta.crossover(direction, 0) and adxVal > adxTh',
      atrMult: 2.5,
    }),
  },
  {
    id: 'R1_VWAP_MeanReversion',
    round: 1,
    concept: 'Session VWAP +/-2 stdev bands, fade extremes back toward VWAP',
    hypothesis: 'Widely used intraday mean-reversion concept — price should snap back to VWAP after 2-sigma stretches.',
    pineSource: wrapMeanRev({
      title: 'BTC VWAP Reversion',
      inputs: `devLen = input.int(20, "Deviation Length")\ndevMult = input.float(2.0, "Deviation Mult")`,
      indicators: `vwapVal = ta.vwap(hlc3)\ndevVal = ta.stdev(close - vwapVal, devLen)\nupperBand = vwapVal + devVal * devMult\nlowerBand = vwapVal - devVal * devMult`,
      longCond: 'ta.crossunder(close, lowerBand)',
      shortCond: 'ta.crossover(close, upperBand)',
      stopMult: 1.5, targetMult: 2.5,
    }),
  },
  {
    id: 'R1_LiquiditySweep_Pivot',
    round: 1,
    concept: 'ICT-style liquidity sweep: wick pierces a confirmed swing high/low then closes back inside — fade the stop-hunt',
    hypothesis: 'Smart-money/ICT concept — stop-hunt wicks beyond swing points followed by a close-back-inside should mark exhaustion.',
    pineSource: wrapMeanRev({
      title: 'BTC Liquidity Sweep',
      inputs: `pivLen = input.int(5, "Pivot Bars Each Side")`,
      indicators: `pl = ta.pivotlow(low, pivLen, pivLen)\nph = ta.pivothigh(high, pivLen, pivLen)\nlastPL = ta.valuewhen(not na(pl), pl, 0)\nlastPH = ta.valuewhen(not na(ph), ph, 0)`,
      longCond: 'low < lastPL and close > lastPL',
      shortCond: 'high > lastPH and close < lastPH',
      stopMult: 1.2, targetMult: 2.4,
    }),
  },
  {
    id: 'R1_RSI_Divergence',
    round: 1,
    concept: 'Regular bullish/bearish RSI(14) divergence at confirmed 5-bar pivots',
    hypothesis: 'Price making a lower low while RSI makes a higher low (and vice versa) is a classic reversal signal.',
    pineSource: wrapMeanRev({
      title: 'BTC RSI Divergence',
      inputs: `rsiLen = input.int(14, "RSI Length")\npivLen = input.int(5, "Pivot Bars Each Side")`,
      indicators: `rsiVal = ta.rsi(close, rsiLen)\npl = ta.pivotlow(low, pivLen, pivLen)\nph = ta.pivothigh(high, pivLen, pivLen)\nrsiAtLow = ta.valuewhen(not na(pl), rsiVal[pivLen], 0)\nprevLow = ta.valuewhen(not na(pl), pl, 1)\nprevRsiAtLow = ta.valuewhen(not na(pl), rsiAtLow, 1)\nrsiAtHigh = ta.valuewhen(not na(ph), rsiVal[pivLen], 0)\nprevHigh = ta.valuewhen(not na(ph), ph, 1)\nprevRsiAtHigh = ta.valuewhen(not na(ph), rsiAtHigh, 1)\nbullDiv = not na(pl) and pl < prevLow and rsiAtLow > prevRsiAtLow\nbearDiv = not na(ph) and ph > prevHigh and rsiAtHigh < prevRsiAtHigh`,
      longCond: 'bullDiv',
      shortCond: 'bearDiv',
      stopMult: 1.5, targetMult: 3.0,
    }),
  },
  {
    id: 'R1_BB_KC_Squeeze',
    round: 1,
    concept: 'TTM-squeeze analog: Bollinger(20,2) inside Keltner(20,1.5) = compression, trade the release direction via momentum',
    hypothesis: 'Volatility contraction (squeeze) reliably precedes expansion — trading the release direction should catch the initial thrust.',
    pineSource: wrapTrend({
      title: 'BTC BB-KC Squeeze',
      inputs: `bbLen = input.int(20, "BB Length")\nbbMult = input.float(2.0, "BB Mult")\nkcLen = input.int(20, "KC Length")\nkcMult = input.float(1.5, "KC Mult")\nmomLen = input.int(12, "Momentum Length")`,
      indicators: `[bbMid, bbUpper, bbLower] = ta.bb(close, bbLen, bbMult)\n[kcMid, kcUpper, kcLower] = ta.kc(close, kcLen, kcMult)\nsqueezeOn = bbLower > kcLower and bbUpper < kcUpper\nsqueezeRelease = squeezeOn[1] and not squeezeOn\nmomVal = ta.mom(close, momLen)`,
      longCond: 'squeezeRelease and momVal > 0',
      shortCond: 'squeezeRelease and momVal < 0',
      atrMult: 2.0,
    }),
  },
  {
    id: 'R1_ZScore_VolFiltered',
    round: 1,
    concept: 'Z-score(50) mean reversion vs SMA(50), only active when ATR% is below its own 100-bar average (avoid high-vol chop)',
    hypothesis: 'Research finding: volatility-filtered momentum/reversion improves Sharpe by skipping choppy high-vol regimes.',
    pineSource: wrapMeanRev({
      title: 'BTC ZScore Vol-Filtered',
      inputs: `maLen = input.int(50, "MA Length")\nzTh = input.float(2.0, "Z Threshold")`,
      indicators: `maVal = ta.sma(close, maLen)\nsdVal = ta.stdev(close, maLen)\nzScore = (close - maVal) / sdVal\natrPct = atrVal / close * 100\natrPctAvg = ta.sma(atrPct, 100)\nvolOk = atrPct < atrPctAvg * 1.3`,
      longCond: 'zScore < -zTh and volOk',
      shortCond: 'zScore > zTh and volOk',
      stopMult: 1.5, targetMult: 2.5,
    }),
  },
  {
    id: 'R1_HMA_CMO_Trend',
    round: 1,
    concept: 'Hull MA(21) crossover filtered by Chande Momentum Oscillator(14) sign agreement',
    hypothesis: 'HMA reacts faster than EMA with less lag; CMO sign filter should reduce false crosses in flat momentum.',
    pineSource: wrapTrend({
      title: 'BTC HMA CMO Trend',
      inputs: `hmaLen = input.int(21, "HMA Length")\ncmoLen = input.int(14, "CMO Length")`,
      indicators: `hmaVal = ta.hma(close, hmaLen)\ncmoVal = ta.cmo(close, cmoLen)`,
      longCond: 'ta.crossover(close, hmaVal) and cmoVal > 0',
      shortCond: 'ta.crossunder(close, hmaVal) and cmoVal < 0',
      atrMult: 2.5,
    }),
  },
  {
    id: 'R1_OBV_DonchianBreakout',
    round: 1,
    concept: 'Donchian(20) breakout confirmed by OBV trending in the same direction (volume-confirmed breakout)',
    hypothesis: 'A breakout backed by rising on-balance-volume should have a higher follow-through rate than price alone.',
    pineSource: wrapTrend({
      title: 'BTC OBV Donchian',
      inputs: `donLen = input.int(20, "Donchian Length")\nobvLen = input.int(20, "OBV Lookback")`,
      indicators: `upperCh = ta.highest(high, donLen)[1]\nlowerCh = ta.lowest(low, donLen)[1]\nobvVal = ta.obv\nobvRising = obvVal > obvVal[obvLen]\nobvFalling = obvVal < obvVal[obvLen]`,
      longCond: 'close > upperCh and obvRising',
      shortCond: 'close < lowerCh and obvFalling',
      atrMult: 2.5,
    }),
  },
  {
    id: 'R1_CCI_RangeReversion',
    round: 1,
    concept: 'CCI(20) crossing back from +/-100 extremes, only in low-ADX (ranging) regime',
    hypothesis: 'CCI reversion should work in genuine ranges but fail in trends — an ADX<20 filter should isolate the good regime.',
    pineSource: wrapMeanRev({
      title: 'BTC CCI Range Reversion',
      inputs: `cciLen = input.int(20, "CCI Length")\nadxLen = input.int(14, "ADX Length")\nadxTh = input.int(20, "ADX Threshold")`,
      indicators: `cciVal = ta.cci(close, cciLen)\n[diPlus, diMinus, adxVal] = ta.dmi(adxLen, adxLen)\nrangeRegime = adxVal < adxTh`,
      longCond: 'ta.crossover(cciVal, -100) and rangeRegime',
      shortCond: 'ta.crossunder(cciVal, 100) and rangeRegime',
      stopMult: 1.5, targetMult: 2.0,
    }),
  },
  {
    id: 'R1_EMA200_Pullback',
    round: 1,
    concept: 'EMA200 macro trend filter, enter on EMA10/EMA20 pullback crosses in the direction of the macro trend',
    hypothesis: 'Trading pullbacks WITH the dominant multi-month trend should have a better win rate than counter-trend or unfiltered crosses.',
    pineSource: wrapTrend({
      title: 'BTC EMA200 Pullback',
      inputs: '',
      indicators: `emaTrend = ta.ema(close, 200)\nemaFast = ta.ema(close, 10)\nemaSlow = ta.ema(close, 20)`,
      longCond: 'close > emaTrend and ta.crossover(emaFast, emaSlow)',
      shortCond: 'close < emaTrend and ta.crossunder(emaFast, emaSlow)',
      atrMult: 2.5,
    }),
  },
  {
    id: 'R1_ParabolicSAR',
    round: 1,
    concept: 'Classic Parabolic SAR(0.02, 0.02, 0.2) flip system',
    hypothesis: 'Baseline trend-follower for comparison — known to whipsaw in chop but never misses a big trend.',
    pineSource: wrapTrend({
      title: 'BTC Parabolic SAR',
      inputs: '',
      indicators: `sarVal = ta.sar(0.02, 0.02, 0.2)`,
      longCond: 'ta.crossover(close, sarVal)',
      shortCond: 'ta.crossunder(close, sarVal)',
      atrMult: 3.0,
    }),
  },
  {
    id: 'R1_WPR_TrendFiltered',
    round: 1,
    concept: 'Williams %R(14) extreme (<-80 / >-20) reversion, only traded in direction of EMA100 trend (i.e. pullback entries)',
    hypothesis: 'WPR extremes signal short-term exhaustion; filtering by the EMA100 trend should turn this into pullback-buying rather than counter-trend fading.',
    pineSource: wrapMeanRev({
      title: 'BTC WPR Trend Filtered',
      inputs: `wprLen = input.int(14, "WPR Length")`,
      indicators: `emaTrend = ta.ema(close, 100)\nwprVal = ta.wpr(wprLen)`,
      longCond: 'wprVal < -80 and close > emaTrend',
      shortCond: 'wprVal > -20 and close < emaTrend',
      stopMult: 1.5, targetMult: 2.5,
    }),
  },
];
